version: '3'

services:
  nginx: # 服务名称
    image: nginx:1.18.0 # 镜像版本
    ports:
      - 80:80 # 暴露端口
    volumes: # 挂载
      - /root/nginx/html:/usr/share/nginx/html
      - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true # 必须，解决Nginx的文件调用的权限问题
  mysql:
    image: mysql:latest
    ports:
    - 3306:3306
    environment: # 指定用户root的密码
      - MYSQL_ROOT_PASSWORD=123456
  redis:
    image: redis:latest
  vueblog:
    image: vueblog:latest
    build: . # 表示以当前目录下的Dockerfile开始构建镜像
    ports:
    - 8081:8081
    depends_on: # 依赖与mysql、redis，可不填，默认 可以
      - mysql
      - redis

