#\u6307\u5B9AmybatisPlus\u626B\u63CF\u7684xml\u6587\u4EF6
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
vueblog:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: authorization
server:
  port: 8081
